// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woazirzgfkfzaewgwpho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvYXppcnpnZmtmemFld2d3cGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Njc2NTYsImV4cCI6MjA2ODI0MzY1Nn0.f5YNSwT0WzfIMs9eErHYihSp30t--DHnOw3WmbFsJnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});